language: generic
sudo: required
servies:
  - docker

before_install:
  - docker build -t arun728/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true arun728/docker-react npm run test

