language: generic
sudo: required
servies:
  - docker

before_install:
  - docker build -t arun728/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true arun728/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-458480478552"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY